// NAPLAN Question Bank for Year 5
// Target: Band 8
// Generated by AI Research Agents - Authentic NAPLAN Patterns

export const naplanQuestions = [
  // ═══════════════════════════════════════════════════════════════
  //  READING - Comprehension, inference, vocabulary
  // ═══════════════════════════════════════════════════════════════
  
  {
    id: 'r1',
    subject: 'Reading',
    year: 5,
    difficulty: 1,
    question: "What does the word 'enormous' mean?",
    options: ["Very small", "Very large", "Very fast", "Very slow"],
    correctAnswer: "Very large",
    explanation: "'Enormous' means extremely large or huge in size."
  },
  {
    id: 'r2',
    subject: 'Reading',
    year: 5,
    difficulty: 1,
    question: "Which word is the opposite of 'ancient'?",
    options: ["Old", "Modern", "Historic", "Aged"],
    correctAnswer: "Modern",
    explanation: "'Ancient' means very old, so 'modern' (new/recent) is the opposite."
  },
  {
    id: 'r3',
    subject: 'Reading',
    year: 5,
    difficulty: 1,
    question: "In the sentence 'The dog barked loudly', what is the adverb?",
    options: ["dog", "barked", "loudly", "The"],
    correctAnswer: "loudly",
    explanation: "An adverb describes how an action is done. 'Loudly' tells us how the dog barked."
  },
  {
    id: 'r4',
    subject: 'Reading',
    year: 5,
    difficulty: 2,
    question: "'The classroom was a zoo.' This is an example of:",
    options: ["Simile", "Metaphor", "Alliteration", "Onomatopoeia"],
    correctAnswer: "Metaphor",
    explanation: "A metaphor says something IS something else. The classroom isn't literally a zoo, but it was chaotic like one."
  },
  {
    id: 'r5',
    subject: 'Reading',
    year: 5,
    difficulty: 2,
    question: "'She ran like the wind.' This is an example of:",
    options: ["Simile", "Metaphor", "Personification", "Hyperbole"],
    correctAnswer: "Simile",
    explanation: "A simile compares two things using 'like' or 'as'. She ran LIKE the wind."
  },
  {
    id: 'r6',
    subject: 'Reading',
    year: 5,
    difficulty: 2,
    question: "What does 'reading between the lines' mean?",
    options: ["Reading very carefully", "Understanding hidden meaning", "Reading every other line", "Using a ruler while reading"],
    correctAnswer: "Understanding hidden meaning",
    explanation: "This idiom means understanding something that isn't directly stated - the hidden meaning."
  },
  {
    id: 'r7',
    subject: 'Reading',
    year: 5,
    difficulty: 2,
    question: "The prefix 'un-' in 'unhappy' means:",
    options: ["Very", "Not", "More", "Again"],
    correctAnswer: "Not",
    explanation: "The prefix 'un-' means 'not'. Unhappy = not happy."
  },
  {
    id: 'r8',
    subject: 'Reading',
    year: 5,
    difficulty: 3,
    question: "In persuasive writing, what is the purpose of emotive language?",
    options: ["To inform the reader", "To influence the reader's feelings", "To describe a scene", "To tell a story"],
    correctAnswer: "To influence the reader's feelings",
    explanation: "Emotive language is used to make readers feel a certain way and persuade them."
  },
  {
    id: 'r9',
    subject: 'Reading',
    year: 5,
    difficulty: 3,
    question: "What does 'bias' mean in a text?",
    options: ["Presenting only one side of an argument", "Giving all the facts", "Being neutral", "Using formal language"],
    correctAnswer: "Presenting only one side of an argument",
    explanation: "Bias means favouring one viewpoint over others, not showing the full picture."
  },
  {
    id: 'r10',
    subject: 'Reading',
    year: 5,
    difficulty: 3,
    question: "The suffix '-ology' means:",
    options: ["Fear of", "Study of", "Full of", "Without"],
    correctAnswer: "Study of",
    explanation: "'-ology' means 'study of'. Biology = study of life, zoology = study of animals."
  },

  // ═══════════════════════════════════════════════════════════════
  //  LANGUAGE CONVENTIONS - Spelling, Grammar, Punctuation
  // ═══════════════════════════════════════════════════════════════

  // Spelling
  {
    id: 'lc1',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 2,
    question: "Which word is spelled correctly?",
    options: ["compitition", "competision", "competition", "compettition"],
    correctAnswer: "competition",
    explanation: "The correct spelling is 'competition'. Common errors include doubling the wrong consonant."
  },
  {
    id: 'lc2',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 1,
    question: "Which underlined word is spelled incorrectly? 'The beautiful garden had diffrent flowers.'",
    options: ["beautiful", "garden", "diffrent", "flowers"],
    correctAnswer: "diffrent",
    explanation: "The correct spelling is 'different'. The word has two 'f's and an 'e' before 'r'."
  },
  {
    id: 'lc3',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 2,
    question: "Which word correctly completes: 'We need to _______ the problem.'",
    options: ["adress", "address", "addres", "adres"],
    correctAnswer: "address",
    explanation: "The correct spelling is 'address' with double 'd' and double 's'."
  },
  {
    id: 'lc4',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 3,
    question: "Which word is spelled correctly?",
    options: ["neccesary", "necessary", "necesary", "neccessary"],
    correctAnswer: "necessary",
    explanation: "Remember: one collar (c) and two sleeves (ss) - necessary."
  },
  {
    id: 'lc5',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 3,
    question: "Which word is spelled correctly?",
    options: ["embarassed", "embarrassed", "embarrased", "embarased"],
    correctAnswer: "embarrassed",
    explanation: "The correct spelling is 'embarrassed' with double 'r' and double 's'."
  },
  {
    id: 'lc6',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 2,
    question: "Which word is spelled correctly?",
    options: ["dissapear", "disappear", "disapear", "dissappear"],
    correctAnswer: "disappear",
    explanation: "The correct spelling is 'disappear' - one 's' and double 'p'."
  },

  // Grammar
  {
    id: 'lc7',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 3,
    question: "Which word correctly completes: 'Neither the teacher nor the students _______ ready.'",
    options: ["was", "were", "is", "be"],
    correctAnswer: "were",
    explanation: "When 'neither...nor' connects subjects, the verb agrees with the nearer subject ('students'), which is plural."
  },
  {
    id: 'lc8',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 1,
    question: "Which sentence is grammatically correct?",
    options: ["Me and Tom went to the shops.", "Tom and me went to the shops.", "Tom and I went to the shops.", "I and Tom went to the shops."],
    correctAnswer: "Tom and I went to the shops.",
    explanation: "'I' is the correct subject pronoun (not 'me'), and it's polite to put the other person first."
  },
  {
    id: 'lc9',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 2,
    question: "Which word correctly completes: 'Each of the boys _______ completed his homework.'",
    options: ["have", "has", "were", "are"],
    correctAnswer: "has",
    explanation: "'Each' is singular and requires the singular verb 'has'."
  },
  {
    id: 'lc10',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 2,
    question: "Which is correct: 'The dog wagged _______ tail excitedly.'",
    options: ["it's", "its", "its'", "their"],
    correctAnswer: "its",
    explanation: "'Its' (no apostrophe) is the possessive form. 'It's' means 'it is'."
  },
  {
    id: 'lc11',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 1,
    question: "Which word correctly completes: 'My sister runs _______ than I do.'",
    options: ["more faster", "fastest", "faster", "more fast"],
    correctAnswer: "faster",
    explanation: "'Faster' is the comparative form. We don't use 'more' with '-er' adjectives."
  },

  // Punctuation
  {
    id: 'lc12',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 2,
    question: "Which sentence has correct punctuation?",
    options: ["\"Where are you going? asked Mum.", "\"Where are you going?\" asked Mum.", "\"Where are you going\" asked Mum?", "Where are you going?\" asked Mum.\""],
    correctAnswer: "\"Where are you going?\" asked Mum.",
    explanation: "The question mark goes inside the closing quotation mark when it's part of the quote."
  },
  {
    id: 'lc13',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 2,
    question: "Which sentence uses the apostrophe correctly?",
    options: ["The childrens' books were on the shelf.", "The children's books were on the shelf.", "The childrens books were on the shelf.", "The children's book's were on the shelf."],
    correctAnswer: "The children's books were on the shelf.",
    explanation: "'Children' is already plural, so we add apostrophe-s ('children's') to show possession."
  },
  {
    id: 'lc14',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 2,
    question: "Where should the comma be placed? 'Although it was raining heavily we still went to the park.'",
    options: ["After 'Although'", "After 'heavily'", "After 'still'", "After 'went'"],
    correctAnswer: "After 'heavily'",
    explanation: "A comma is needed after an introductory clause: 'Although it was raining heavily, we still went.'"
  },
  {
    id: 'lc15',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 1,
    question: "Which sentence has correct punctuation?",
    options: ["I need to buy apples oranges and bananas.", "I need to buy apples, oranges, and bananas.", "I need to buy, apples oranges and bananas.", "I need to buy apples oranges, and bananas."],
    correctAnswer: "I need to buy apples, oranges, and bananas.",
    explanation: "Items in a list should be separated by commas."
  },
  {
    id: 'lc16',
    subject: 'Language Conventions',
    year: 5,
    difficulty: 1,
    question: "Which uses the apostrophe correctly?",
    options: ["Its been a long day.", "It's been a long day.", "Its' been a long day.", "Its been a long day'."],
    correctAnswer: "It's been a long day.",
    explanation: "'It's' is a contraction of 'it has'. The apostrophe shows where letters have been removed."
  },

  // ═══════════════════════════════════════════════════════════════
  //  NUMERACY - Number, Algebra, Measurement, Geometry, Statistics
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'n1',
    subject: 'Numeracy',
    year: 5,
    difficulty: 1,
    question: "What is the value of 7 in the number 47,253?",
    options: ["7", "70", "700", "7000"],
    correctAnswer: "7000",
    explanation: "The digit 7 is in the thousands place. The place value is 7 × 1000 = 7000."
  },
  {
    id: 'n2',
    subject: 'Numeracy',
    year: 5,
    difficulty: 1,
    question: "Which fraction is equivalent to 2/4?",
    options: ["1/4", "1/2", "3/4", "2/8"],
    correctAnswer: "1/2",
    explanation: "2/4 can be simplified: 2÷2 = 1 and 4÷2 = 2. So 2/4 = 1/2."
  },
  {
    id: 'n3',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "A rectangle has a length of 8 cm and a width of 5 cm. What is its perimeter?",
    options: ["13 cm", "26 cm", "40 cm", "80 cm"],
    correctAnswer: "26 cm",
    explanation: "Perimeter = 2 × (length + width) = 2 × (8 + 5) = 2 × 13 = 26 cm."
  },
  {
    id: 'n4',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "What number completes this pattern? 3, 9, 27, ___",
    options: ["30", "36", "54", "81"],
    correctAnswer: "81",
    explanation: "Each number is multiplied by 3: 3 × 3 = 9, 9 × 3 = 27, 27 × 3 = 81."
  },
  {
    id: 'n5',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "Which of these shows 0.35 as a fraction?",
    options: ["35/10", "35/100", "3/5", "35/1000"],
    correctAnswer: "35/100",
    explanation: "0.35 means 35 hundredths = 35/100."
  },
  {
    id: 'n6',
    subject: 'Numeracy',
    year: 5,
    difficulty: 1,
    question: "A bag contains 3 red, 2 blue, and 5 green balls. Which colour are you most likely to pick?",
    options: ["Red", "Blue", "Green", "They are all equally likely"],
    correctAnswer: "Green",
    explanation: "There are 5 green balls (most), so green is most likely."
  },
  {
    id: 'n7',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "If n + 24 = 57, what is the value of n?",
    options: ["23", "33", "43", "81"],
    correctAnswer: "33",
    explanation: "n = 57 - 24 = 33. Check: 33 + 24 = 57 ✓"
  },
  {
    id: 'n8',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "How many lines of symmetry does a square have?",
    options: ["1", "2", "4", "8"],
    correctAnswer: "4",
    explanation: "A square has 4 lines of symmetry: 2 diagonal and 2 through the middle."
  },
  {
    id: 'n9',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "A movie starts at 2:45 pm and runs for 1 hour 35 minutes. When does it finish?",
    options: ["3:80 pm", "4:10 pm", "4:20 pm", "4:35 pm"],
    correctAnswer: "4:20 pm",
    explanation: "2:45 + 1:00 = 3:45. Then 3:45 + 35 min = 4:20 pm."
  },
  {
    id: 'n10',
    subject: 'Numeracy',
    year: 5,
    difficulty: 1,
    question: "What is 3/8 + 2/8?",
    options: ["5/8", "5/16", "6/8", "1/2"],
    correctAnswer: "5/8",
    explanation: "Same denominator: add numerators. 3/8 + 2/8 = 5/8."
  },
  {
    id: 'n11',
    subject: 'Numeracy',
    year: 5,
    difficulty: 3,
    question: "The area of a rectangle is 48 cm². If length is 8 cm, what is the width?",
    options: ["4 cm", "6 cm", "40 cm", "56 cm"],
    correctAnswer: "6 cm",
    explanation: "Area = length × width. So 48 = 8 × width. Width = 48 ÷ 8 = 6 cm."
  },
  {
    id: 'n12',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "A shop sells apples for $0.45 each. How much do 6 apples cost?",
    options: ["$2.40", "$2.60", "$2.70", "$4.50"],
    correctAnswer: "$2.70",
    explanation: "6 × $0.45 = $2.70."
  },
  {
    id: 'n13',
    subject: 'Numeracy',
    year: 5,
    difficulty: 1,
    question: "What is the next number? 0.5, 1.0, 1.5, 2.0, ___",
    options: ["2.25", "2.5", "3.0", "2.05"],
    correctAnswer: "2.5",
    explanation: "Pattern increases by 0.5 each time: 2.0 + 0.5 = 2.5."
  },
  {
    id: 'n14',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "A spinner has 4 equal sections: red, blue, yellow, green. What is the probability of landing on blue?",
    options: ["1/2", "1/3", "1/4", "4/4"],
    correctAnswer: "1/4",
    explanation: "1 blue out of 4 equal sections = 1/4."
  },
  {
    id: 'n15',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "Which angle is obtuse?",
    options: ["45°", "90°", "120°", "180°"],
    correctAnswer: "120°",
    explanation: "Obtuse angles are greater than 90° but less than 180°. 120° is obtuse."
  },
  {
    id: 'n16',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "Sarah has 3.5 metres of ribbon. She uses 1.8 metres. How much is left?",
    options: ["1.3 m", "1.7 m", "2.3 m", "5.3 m"],
    correctAnswer: "1.7 m",
    explanation: "3.5 - 1.8 = 1.7 metres."
  },
  {
    id: 'n17',
    subject: 'Numeracy',
    year: 5,
    difficulty: 1,
    question: "A cube has how many faces?",
    options: ["4", "6", "8", "12"],
    correctAnswer: "6",
    explanation: "A cube has 6 faces: top, bottom, front, back, left and right."
  },
  {
    id: 'n18',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "If 4 × n = 36, what is n?",
    options: ["6", "8", "9", "32"],
    correctAnswer: "9",
    explanation: "n = 36 ÷ 4 = 9. Check: 4 × 9 = 36 ✓"
  },
  {
    id: 'n19',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "In a pictograph, ★ = 4 books. Ben has ★★★. How many books did Ben read?",
    options: ["3", "7", "12", "34"],
    correctAnswer: "12",
    explanation: "3 stars × 4 books = 12 books."
  },
  {
    id: 'n20',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "What is 2.56 rounded to one decimal place?",
    options: ["2.5", "2.6", "3.0", "2.50"],
    correctAnswer: "2.6",
    explanation: "Look at second decimal (6). Since 6 ≥ 5, round up: 2.56 → 2.6."
  },
  {
    id: 'n21',
    subject: 'Numeracy',
    year: 5,
    difficulty: 3,
    question: "Tom scored 78, 85, 92 and 81. What is his mean (average)?",
    options: ["82", "84", "85", "86"],
    correctAnswer: "84",
    explanation: "Mean = (78 + 85 + 92 + 81) ÷ 4 = 336 ÷ 4 = 84."
  },
  {
    id: 'n22',
    subject: 'Numeracy',
    year: 5,
    difficulty: 2,
    question: "Which list is in order from smallest to largest?",
    options: ["0.5, 0.09, 0.45, 0.8", "0.09, 0.45, 0.5, 0.8", "0.8, 0.5, 0.45, 0.09", "0.45, 0.09, 0.5, 0.8"],
    correctAnswer: "0.09, 0.45, 0.5, 0.8",
    explanation: "Convert to hundredths: 9, 45, 50, 80. Smallest to largest."
  },

  // ═══════════════════════════════════════════════════════════════
  //  WRITING - Skills for persuasive and narrative writing
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'w1',
    subject: 'Writing',
    year: 5,
    difficulty: 2,
    question: "Which opening would be MOST effective for a persuasive text?",
    options: ["I think we need more playground equipment.", "Have you ever waited 20 minutes just to use a swing? Our school desperately needs more playground equipment.", "Playground equipment is good for kids.", "This essay is about playground equipment."],
    correctAnswer: "Have you ever waited 20 minutes just to use a swing? Our school desperately needs more playground equipment.",
    explanation: "Uses a rhetorical question to engage the reader, states a clear position, and signals reasons will follow."
  },
  {
    id: 'w2',
    subject: 'Writing',
    year: 5,
    difficulty: 1,
    question: "Which sentence contains the STRONGEST persuasive language?",
    options: ["Some students might like longer lunch breaks.", "Longer lunch breaks would probably be okay.", "Extending lunch breaks is absolutely essential for student wellbeing.", "Lunch breaks could maybe be a bit longer."],
    correctAnswer: "Extending lunch breaks is absolutely essential for student wellbeing.",
    explanation: "Uses powerful words like 'absolutely essential' and connects to values the audience cares about."
  },
  {
    id: 'w3',
    subject: 'Writing',
    year: 5,
    difficulty: 2,
    question: "What is the correct structure for a persuasive text?",
    options: ["Orientation → Complication → Resolution", "Introduction with position → Arguments with evidence → Conclusion with call to action", "Setting → Characters → Problem → Solution", "Topic sentence → Random facts → Opinion"],
    correctAnswer: "Introduction with position → Arguments with evidence → Conclusion with call to action",
    explanation: "Persuasive texts state your position, present arguments with evidence, and conclude with a call to action."
  },
  {
    id: 'w4',
    subject: 'Writing',
    year: 5,
    difficulty: 2,
    question: "For building suspense in a narrative, which paragraph structure is MOST effective?",
    options: ["One long paragraph describing everything", "Short, punchy paragraphs that break up the action", "No paragraphs to keep the story flowing", "Alphabetical paragraphs"],
    correctAnswer: "Short, punchy paragraphs that break up the action",
    explanation: "Short paragraphs create tension by controlling pace and forcing pauses."
  },
  {
    id: 'w5',
    subject: 'Writing',
    year: 5,
    difficulty: 1,
    question: "Which is the BEST topic sentence to begin a paragraph?",
    options: ["Dogs are cute. Cats are nice.", "There are many reasons why homework should be limited.", "First of all, secondly, thirdly.", "In conclusion, that is why."],
    correctAnswer: "There are many reasons why homework should be limited.",
    explanation: "A topic sentence introduces the main idea and tells the reader what to expect."
  },
  {
    id: 'w6',
    subject: 'Writing',
    year: 5,
    difficulty: 3,
    question: "How could 'The dog barked. The dog ran. The dog jumped.' be improved for variety?",
    options: ["The dog barked, ran, jumped.", "The dog barked and the dog ran and the dog jumped.", "Barking excitedly, the energetic dog bounded across the yard before leaping high.", "A dog did some things."],
    correctAnswer: "Barking excitedly, the energetic dog bounded across the yard before leaping high.",
    explanation: "Uses varied sentence structure, descriptive vocabulary, and combines actions smoothly."
  },
  {
    id: 'w7',
    subject: 'Writing',
    year: 5,
    difficulty: 2,
    question: "Which shows the BEST use of connectives?",
    options: ["Recycling helps. Recycling reduces. Recycling saves.", "Recycling helps and it reduces and it saves.", "Recycling helps the environment. Furthermore, it reduces waste. Additionally, it saves energy.", "Recycling. Environment. Waste. Energy."],
    correctAnswer: "Recycling helps the environment. Furthermore, it reduces waste. Additionally, it saves energy.",
    explanation: "Connectives like 'Furthermore' and 'Additionally' show relationships between ideas."
  },
  {
    id: 'w8',
    subject: 'Writing',
    year: 5,
    difficulty: 1,
    question: "Which word BEST replaces 'said' in: 'The angry teacher said at the noisy students.'",
    options: ["told", "bellowed", "whispered", "asked"],
    correctAnswer: "bellowed",
    explanation: "'Bellowed' matches the emotion (angry) and situation (trying to quiet noisy students)."
  },
  {
    id: 'w9',
    subject: 'Writing',
    year: 5,
    difficulty: 2,
    question: "For a formal audience (like a principal), which phrase is MOST appropriate?",
    options: ["Hey, I reckon we should get more computers, yeah?", "I respectfully request that the school consider investing in additional computer resources.", "Computers are cool and we need heaps more!", "Whatever, just buy more computers."],
    correctAnswer: "I respectfully request that the school consider investing in additional computer resources.",
    explanation: "Formal language includes polite phrases, sophisticated vocabulary, and complete sentences."
  },
  {
    id: 'w10',
    subject: 'Writing',
    year: 5,
    difficulty: 2,
    question: "Which evidence would be MOST convincing for longer recess times?",
    options: ["My friend thinks recess is too short.", "Research shows students with longer breaks perform 15% better in afternoon classes.", "Recess is fun and everyone likes it.", "I just really want longer recess."],
    correctAnswer: "Research shows students with longer breaks perform 15% better in afternoon classes.",
    explanation: "Statistics and research are more convincing than personal opinions."
  },
  {
    id: 'w11',
    subject: 'Writing',
    year: 5,
    difficulty: 1,
    question: "In narrative writing, what is the purpose of the 'complication'?",
    options: ["To introduce characters and setting", "To create a problem the character must overcome", "To wrap up the story", "To describe the weather"],
    correctAnswer: "To create a problem the character must overcome",
    explanation: "The complication creates tension and drives the plot forward."
  },
  {
    id: 'w12',
    subject: 'Writing',
    year: 5,
    difficulty: 3,
    question: "Which shows CORRECT use of a complex sentence?",
    options: ["I went and played and had ice cream.", "Although it was raining heavily, Sarah decided to walk anyway.", "The park. Playing. Swings.", "Running to the store because milk."],
    correctAnswer: "Although it was raining heavily, Sarah decided to walk anyway.",
    explanation: "Contains an independent clause and subordinate clause ('Although it was raining heavily')."
  },
  {
    id: 'w13',
    subject: 'Writing',
    year: 5,
    difficulty: 2,
    question: "Which conclusion is MOST effective for a persuasive text about reducing plastic?",
    options: ["That's all I have to say about plastic.", "The end.", "In conclusion, reducing plastic use is vital for our planet's future. Let's act now before it's too late.", "Plastic is bad, I guess."],
    correctAnswer: "In conclusion, reducing plastic use is vital for our planet's future. Let's act now before it's too late.",
    explanation: "Summarises the argument, reinforces position, and includes a call to action."
  },
  {
    id: 'w14',
    subject: 'Writing',
    year: 5,
    difficulty: 2,
    question: "What is 'Show, don't tell' in narrative writing?",
    options: ["To make the story shorter", "To create vivid imagery by describing actions and feelings rather than stating them", "To avoid adjectives", "To tell the reader exactly what to think"],
    correctAnswer: "To create vivid imagery by describing actions and feelings rather than stating them",
    explanation: "Instead of 'She was scared', show it: 'Her hands trembled as she backed against the wall.'"
  },
  {
    id: 'w15',
    subject: 'Writing',
    year: 5,
    difficulty: 3,
    question: "Which shows BEST sentence variety in openers?",
    options: ["I went to the shop. I bought milk. I walked home. I made dinner.", "The shop was where I went. Milk was what I bought.", "After school, I headed to the shop. Grabbing a carton, I paid quickly. Soon, I was walking home.", "Shop milk home dinner."],
    correctAnswer: "After school, I headed to the shop. Grabbing a carton, I paid quickly. Soon, I was walking home.",
    explanation: "Uses time phrases, participial phrases, and adverbs to vary sentence beginnings."
  }
];

// Subject configuration for NAPLAN
export const naplanSubjects = ['Reading', 'Language Conventions', 'Numeracy', 'Writing'];

// Export question count by subject
export const getQuestionStats = () => {
  const stats = {};
  naplanSubjects.forEach(subject => {
    stats[subject] = naplanQuestions.filter(q => q.subject === subject).length;
  });
  return stats;
};
